#!/usr/bin/env python3

from pathlib import Path

FAILURES = [
    "atomicrmw-expand.ll",
    "basic-branch.ll",
    "bb-prolog-spill-during-regalloc.ll",
    "cf-loop-on-constant.ll",
    "collapse-endcf.ll",
    "control-flow-fastregalloc.ll",
    "dagcombine-lshr-and-cmp.ll",
    "div_i128.ll",
    "indirect-addressing-si.ll",
    "indirect-addressing-term.ll",
    "insert-delay-alu-bug.ll",
    "kernel-vgpr-spill-mubuf-with-voffset.ll",
    "llvm.amdgcn.ds.gws.barrier-fastregalloc.ll",
    "llvm.amdgcn.update.dpp.ll",
    "llvm.dbg.value.ll",
    "load-global-invariant.ll",
    "memory-legalizer-flat-agent.ll",
    "memory-legalizer-flat-cluster.ll",
    "memory-legalizer-flat-lastuse.ll",
    "memory-legalizer-flat-nontemporal.ll",
    "memory-legalizer-flat-singlethread.ll",
    "memory-legalizer-flat-system.ll",
    "memory-legalizer-flat-volatile.ll",
    "memory-legalizer-flat-wavefront.ll",
    "memory-legalizer-flat-workgroup.ll",
    "memory-legalizer-global-agent.ll",
    "memory-legalizer-global-cluster.ll",
    "memory-legalizer-global-lastuse.ll",
    "memory-legalizer-global-nontemporal.ll",
    "memory-legalizer-global-singlethread.ll",
    "memory-legalizer-global-system.ll",
    "memory-legalizer-global-volatile.ll",
    "memory-legalizer-global-wavefront.ll",
    "memory-legalizer-global-workgroup.ll",
    "memory-legalizer-local-agent.ll",
    "memory-legalizer-local-cluster.ll",
    "memory-legalizer-local-nontemporal.ll",
    "memory-legalizer-local-singlethread.ll",
    "memory-legalizer-local-system.ll",
    "memory-legalizer-local-volatile.ll",
    "memory-legalizer-local-wavefront.ll",
    "memory-legalizer-local-workgroup.ll",
    "memory-legalizer-private-agent.ll",
    "memory-legalizer-private-cluster.ll",
    "memory-legalizer-private-lastuse.ll",
    "memory-legalizer-private-nontemporal.ll",
    "memory-legalizer-private-singlethread.ll",
    "memory-legalizer-private-system.ll",
    "memory-legalizer-private-volatile.ll",
    "memory-legalizer-private-wavefront.ll",
    "memory-legalizer-private-workgroup.ll",
    "partial-sgpr-to-vgpr-spills.ll",
    "rem_i128.ll",
    "rewrite-vgpr-mfma-to-agpr.ll",
    "scalar_to_vector_v2x16.ll",
    "select-phi-s16-fp.ll",
    "sgpr-spill-no-vgprs.ll",
    "sgpr-spills-split-regalloc.ll",
    "smfmac_alloc_failure_no_agpr_O0.ll",
    "sopk-no-literal.ll",
    "spill-m0.ll",
    "spill-vgpr-to-agpr-update-regscavenger.ll",
    "spill-wide-sgpr.ll",
    "stacksave_stackrestore.ll",
    "swdev503538-move-to-valu-stack-srd-physreg.ll",
    "trap-abis.ll",
    "vgpr-limit-gfx1250.ll",
    "vgpr-spill-placement-issue61083.ll",
    "vgpr_constant_to_sgpr.ll",
    "wwm-reserved-spill.ll",
    "wwm-reserved.ll",
    "zext-lid.ll",
]


def main() -> None:
    root = Path(__file__).resolve().parent.parent / "llvm" / "test" / "CodeGen" / "AMDGPU"
    categories = {"llc": [], "mir": [], "manual": []}

    for rel_path in FAILURES:
        path = root / rel_path
        if not path.exists():
            categories.setdefault("missing", []).append(rel_path)
            continue
        header = "\n".join(path.read_text().splitlines()[:6])
        if "update_mir_test_checks.py" in header:
            categories["mir"].append(rel_path)
        elif "update_llc_test_checks.py" in header:
            categories["llc"].append(rel_path)
        else:
            categories["manual"].append(rel_path)

    print(f"Autogenerated LLC tests: {len(categories['llc'])}")
    for name in categories["llc"]:
        print(f"  {name}")
    print()

    print(f"Autogenerated MIR tests: {len(categories['mir'])}")
    for name in categories["mir"]:
        print(f"  {name}")
    print()

    print(f"Manual tests: {len(categories['manual'])}")
    for name in categories["manual"]:
        print(f"  {name}")

    if categories.get("missing"):
        print()
        print(f"Missing files: {len(categories['missing'])}")
        for name in categories["missing"]:
            print(f"  {name}")


if __name__ == "__main__":
    main()

